# @format

name: build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: "13.10"
      - name: Install npm and run 
        run: |
          npm i
          npm run build
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ry3iezn/calendar_app_test/calendarfrontserver
          registry: docker.pkg.github.com
          username: secrets.USERNAME_NAME
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./Dockerfile
          tags: latest
      - name: Deploy package to your instance
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: secrets.USERNAME_NAME
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: 139.162.251.16
          username: secrets.HOST_USER
          password: Linode123#Linode123#
          port: 22
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q)
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/ry3iezn/calendar_app_test/calendarfrontend:latest
            docker run -dit -p 3000:3000 docker.pkg.github.com/ry3iezn/calendar_app_test/calendarfrontend:latest

